# yaml-language-server: $schema=https://raw.githubusercontent.com/goreleaser/goreleaser/v2.18.2/www/static/schema.json
version: 2

project_name: tronwatch

builds:
  - id: tronwatch
    main: ./cmd/tronwatch
    binary: tronwatch
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/yooud/tronwatch/internal/version.Value={{ .Version }}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - ids:
      - tronwatch
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt
  algorithm: sha256

sboms:
  - artifacts: archive

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"

release:
  prerelease: auto

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"
